name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java (Spring Boot 3 requires Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptium'

      # Cache dependencies to speed up builds
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project using Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Run tests (optional)
      - name: Run tests
        run: mvn test

      # If you want to build the Docker image for deployment (optional)
      - name: Build Docker image
        run: docker build -t your-image-name .

      # Deploy to a server or container registry (optional step)
      - name: Deploy to Docker Hub (or other registry)
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push your-image-name:latest
